server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shiro?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql123
    #使用com.mysql.jdbc.Driver也行，但是会报WARN
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
  #是否在log显示sql语句
    show-sql: true
    #使用的数据库为Orancle、Mysql、sqlServer等
    database: mysql
    #自动生成表和自动更新字段
    hibernate:
      ddl-auto: update
  cache:
    redis:
      time-to-live: 60s
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000s
    lettuce:
      pool:
        max-idle: 10
        max-active: 10
        min-idle: 5
        max-wait: 10000s
    database: 0
